{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhangyue.lancet",
    "module": "lancet-plugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lancet-plugin-0.0.1.jar",
          "url": "lancet-plugin-0.0.1.jar",
          "size": 149748,
          "sha512": "2bd8d3ef93fa375d3c355c9736379253bc9ad72ed85ee3fe96c7a90274aafddb30260a503203041121345e707d11bb35552c482e9bbb173da6027e60c7fd5bcc",
          "sha256": "8798cb8976b4035862b93d53904c94cbe086e8a7faae4e7773e256ec7f2a2bdd",
          "sha1": "2ae5b9b21f4002e5d4308684a8d31fd99729f0e3",
          "md5": "b723fd46a32cd86aea651de5d371199e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.heyan224",
          "module": "lancet-runtime",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bytedance.android.byteX",
          "module": "common",
          "version": {
            "requires": "0.3.0"
          },
          "excludes": [
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            }
          ]
        },
        {
          "group": "com.bytedance.android.byteX",
          "module": "PluginConfigProcessor",
          "version": {
            "requires": "0.3.0"
          },
          "excludes": [
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lancet-plugin-0.0.1.jar",
          "url": "lancet-plugin-0.0.1.jar",
          "size": 149748,
          "sha512": "2bd8d3ef93fa375d3c355c9736379253bc9ad72ed85ee3fe96c7a90274aafddb30260a503203041121345e707d11bb35552c482e9bbb173da6027e60c7fd5bcc",
          "sha256": "8798cb8976b4035862b93d53904c94cbe086e8a7faae4e7773e256ec7f2a2bdd",
          "sha1": "2ae5b9b21f4002e5d4308684a8d31fd99729f0e3",
          "md5": "b723fd46a32cd86aea651de5d371199e"
        }
      ]
    }
  ]
}
