{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhangyue.lancet",
    "module": "lancet-plugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lancet-plugin-0.0.1.jar",
          "url": "lancet-plugin-0.0.1.jar",
          "size": 143715,
          "sha512": "710d73088f7990661bfd984743b46f7554d59b3ca96db769ea86d823fecef04a1b6e69b20c55f2fac9fa60802b3b8f24d839ab464dd9f449f964d3ca36f454e1",
          "sha256": "b072a5165fccccf65c1adfdb9de0c0d54bced8ef04fdb71eff0a57f6a9683469",
          "sha1": "88560bc3180ea00fb70298b8b16081cfc3eb5788",
          "md5": "0856bf2dab91ab43470a993e4f9ad502"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.heyan224",
          "module": "lancet-runtime",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bytedance.android.byteX",
          "module": "common",
          "version": {
            "requires": "0.3.0"
          },
          "excludes": [
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            }
          ]
        },
        {
          "group": "com.bytedance.android.byteX",
          "module": "PluginConfigProcessor",
          "version": {
            "requires": "0.3.0"
          },
          "excludes": [
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lancet-plugin-0.0.1.jar",
          "url": "lancet-plugin-0.0.1.jar",
          "size": 143715,
          "sha512": "710d73088f7990661bfd984743b46f7554d59b3ca96db769ea86d823fecef04a1b6e69b20c55f2fac9fa60802b3b8f24d839ab464dd9f449f964d3ca36f454e1",
          "sha256": "b072a5165fccccf65c1adfdb9de0c0d54bced8ef04fdb71eff0a57f6a9683469",
          "sha1": "88560bc3180ea00fb70298b8b16081cfc3eb5788",
          "md5": "0856bf2dab91ab43470a993e4f9ad502"
        }
      ]
    }
  ]
}
